/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-103926-gda5497a1a2-odin-ffmpeg-20211001"
#endif /* AVUTIL_FFVERSION_H */
